### ISSUE TITLE
Add vertex id XML attribute as graph attribute ?

### ISSUE THREAD

**Issue by sandrokeil** [graphp/graphml#14]
Since [the vertex id is dropped](https://github.com/graphp/graph/issues/131), how does this library handles it? Should the `id` XML attribute added as an graph attribute?

**Comment by clue** [comment]
Exactly, this project should default to assigning the XML `id` attribute to the `id` vertex attribute by default and vice versa. This implies that the vertex `id` attribute is no longer required, so we need to automatically assign one if it's not explicitly assigned. See also https://github.com/graphp/graphviz/pull/40/commits/2ea74b9f7a407ca0667ce0249febffafae547a6b for details :+1:
