### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by clue** [graphp/graphml#4]
- Quickstart example
- API usage
- Examples

**Comment by ftrotter** [comment]
To be frank: There are 100 ways this software could work. No one is going to be able to make the basic low level documentation but you. Everyone else would have to struggle to reverse engineer how to use the software from the sourcecode... then contribute documentation. No one is going to do that. 

However, if you started the documentation and showed just the very basics of how to use your library, then you would find that your adoption, and later your contributions would go way up. You are essentially looking for another core developer out of the gate and you are never going to get that. 

At this point is is actually easier to use something like this in python: 

http://hadim.fr/pygraphml/usage.html

Then it is to start to learn your library.

**Comment by clue** [comment]
I understand the current situation may be frustrating, but this project has been written solely in my spare free time. If you need professional help for a commercial project, please contact me via email and I'm sure we can arrange this :)

For the time being, consider taking a look at the examples, in particular it also includes a functional example which shows how to export and import a graphml file.
